### ISSUE TITLE
Can't get a value as string nested more than three levels deep. 

### ISSUE THREAD

**Issue by umarsear** [neslib/Neslib.Json#1]
If I try and retrieve a value that is nested more than four or more level deep as a string, I get an exception, is this expected behavior?

example 

{ "store": {
    "book": [
      { "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95,
		    "Sale" : {
			    "OnSale" : "Yes"
		    }
      },
      { "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
}

Retrieving $.store.book[0].Sale.OnSale as toJson works, however if I try asString it does not. toJson returns {
  "OnSale" : "Yes"
}, though!

procedure TForm5.Button3Click(Sender: TObject);
var
  Matches: TArray<TJsonValue>;
begin
  JSONDoc:=TJsonDocument.Parse(memo1.Text);
  matches:=TJsonPath.Match(JSONDoc,'$.'+edit1.Text);
  label1.Caption:=matches[0].ToJson();
  label1.Caption:=matches[0].ToString();
end;

**Comment by neslib** [comment]
Good catch! There was an issue with resizing the expression operator array once it becomes full (after 4 operators in this case).

The issue should be fixed now.
