### ISSUE TITLE
H2443 Inline function 'TJsonValue.TryGetValue' has not been expanded

### ISSUE THREAD

**Issue by vincentparrett** [neslib/Neslib.Json#11]
Delphi 11.1 is reporting this :

```[dcc32 Hint] Neslib.Json.Path.pas(847): H2443 Inline function 'TJsonValue.TryGetValue' has not been expanded because unit 'System.Classes' is not specified in USES list```

I will submit a PR.

**Comment by neslib** [comment]
Thank you for this contribution! The PR has been merged.
