### ISSUE TITLE
Neslib vs GrijjyFoundation

### ISSUE THREAD

**Issue by vincentparrett** [neslib/Neslib.Json#5]
Looking for a json parser that fully support jsonpath - and there seems to be some similarity between neslib and GrijjyFoundation (same developers?) - so which should I chose? This one seems to have more recent commits (well to the json code anyway).

**Comment by neslib** [comment]
I wrote both libraries. I wrote the GrijjyFoundation library first but wanted to experiment with a different kind of implementation which is smaller, a bit faster, uses a bit less memory and is (arguably) a bit easier to use. That library turned into Neslib.Json.

Functionality wise, both libraries are very similar when it comes to pure JSON. So it may be a matter of personal preference.
The GrijjyFoundation version has more features not directly related to JSON, such as support for BSON and serialization.

You could take quick look the samples/unit tests in both version to check which API you prefer.

**Comment by vincentparrett** [comment]
Thanks. I like this one better so far ;)

**Comment by dslutej** [comment]
@vincentparrett , it is pretty awesome. 👍
